# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_treasures_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasures',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
