# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-27 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_treasures_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasures',
            name='image',
            field=models.ImageField(default='media/default.png', upload_to='media/treasure_images'),
        ),
    ]
